name: tejas_tutoring_app
description: Tejas - Online Tutoring Platform Mobile App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.21
  form_field_validator: ^1.1.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
